name: flutter_slash
description: "Flutter Slash is a 2D hack and slash game."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flame_audio: ^2.10.6
  flame_tiled: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/player/
    - assets/images/chicken/
    - assets/images/weapons/sprites/guns/
    - assets/images/weapons/sprites/ammo/ak-47/
    - assets/images/weapons/animations/ak-47/
    - assets/audio/
    - assets/audio/sfx/
