name: flutter_slash
description: "Flutter Slash is a 2D hack and slash game."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flame_audio: ^2.10.6
  flame_tiled: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/flutter-slash.tmx
    - assets/tiles/flutter-slash.tsx
    - assets/images/pipo-nekonin.png
    - assets/images/tileset.png
    - assets/images/weapons/sprites/guns/AK-47.png
    - assets/images/weapons/sprites/ammo/ak-47/bullet.png
    - assets/images/weapons/animations/AK-47/Full-auto/Full_auto_muzzle_AK-47.png
    - assets/audio/
    - assets/images/Chicken/
